### ISSUE TITLE
[Suggestion] Bioreactor entries for Forestry saplings

### ISSUE THREAD

**Issue by gdm413229** [JackyyTV/IntegrationForegoing#40]
Integration Foregoing's Forestry-related stuff currently doesn't have bioreactor entries for Forestry's saplings.  Vanilla saplings can be processed in the Bioreactor for biofuel production, could be handy if there's a way for Forestry saplings to be made into biofuel when stockpiles of saplings can't fit inside your arborist's chests.

**Comment by JackyyTV** [comment]
I did actually tried to add support for this way back when Integration Foregoing was initially released, however, since Forestry uses NBT data to store data for each different saplings, it completely broke the Industrial Foregoing API, so it failed rather badly. Support for Forestry saplings will probably never gets added because of that, sorry.
