### ISSUE TITLE
AgriCraft seeds on crop sticks using the plant sower

### ISSUE THREAD

**Issue by Shwat** [JackyyTV/IntegrationForegoing#43]
Hi, Was hoping to use industrial foregoing to automate some AgriCraft farms. The plant sower doesn't accept any AgriCraft seeds or even plant regular seeds onto cropsticks.

**Comment by JackyyTV** [comment]
The Plant Gatherer does work with AgriCraft crops, but you have to plant the seeds manually, you can't use the Plant Sower for now.

Sadly, the API in Industrial Foregoing is fairly limited and since this mod heavily relies on the API, there's not much I can do about it, you'd have to suggest that in the [Industrial Foregoing](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues) repository.
