### ISSUE TITLE
[Suggestion] Random Things support

### ISSUE THREAD

**Issue by OmegaPaladin** [JackyyTV/IntegrationForegoing#48]
I'd really like to be able to use Industrial Foregoing with Random Things.  https://www.curseforge.com/minecraft/mc-mods/random-things

Spectre Trees could be associated with the farming system
https://lumien.net/rtwiki/blocks/spectre-sapling/

Glowing Mushrooms could be added to the spore recreator as well

**Comment by JackyyTV** [comment]
Added in [1.10](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing/files/2904594), unfortunately though, I was not able to add a special Plant Gatherer handler for the Spectre Trees since the tree harvesting part of the Plant Gatherer is tied to Industrial Foregoing itself, and my addon only has very limited access to the API.
However, I did add a special Plant Gatherer handler for the Lotus, hope you'll find that useful for farming EXP (Lotus can be consumed for EXP), and I've also added a few Bioreactor entries.
