### ISSUE TITLE
No laser drill entry for Applied Energistics 2 certus quartz ore

### ISSUE THREAD

**Issue by GrantGryczan** [JackyyTV/IntegrationForegoing#49]
[Here](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing), it says there is laser drill integration with AE2.
![image](https://user-images.githubusercontent.com/14056899/73783536-dd64ec00-4761-11ea-930a-303136bf23bb.png)
But when I check JEI, certus quartz ore has no laser drill recipes, and charged certus quartz only has recipes from charging normal certus quartz.

I'm using IntegrationForegoing-1.12.2-1.9.jar and appliedenergistics2-rv6-stable-7.jar, both which are currently the latest release.

**Comment by JackyyTV** [comment]
Maybe AE2 has changed the block IDs or something on their side, I'll have a
look into it when I have time after work.

**Comment by JackyyTV** [comment]
What modpack are you playing? I just checked the recipes for both the certus ores in my dev environment and they are showing up as intended.
![image](https://user-images.githubusercontent.com/11830494/73914154-a7f00800-48f3-11ea-974a-1045fa9d815c.png)
There is a possibiliy that the modpack you're playing has the OreDict `oreCertusQuartz` and `oreChargedCertusQuartz` removed somehow, which is causing the integration to be broken as the laser drill entries heavily relies on OreDict.

**Comment by GrantGryczan** [comment]
I am not playing any particular modpack. I just installed the mod with the default config. I didn't see certus quartz in the laser drill ore JSON. When I added an entry for `oreCertusQuartz` it worked fine.

**Comment by JackyyTV** [comment]
That's really odd. I've just tested this again on a completely fresh install of a custom pack with only the following mods installed on Forge 2847:
![image](https://user-images.githubusercontent.com/11830494/74795072-ee843000-52ff-11ea-8620-d490e6f99953.png)
And it appears to have worked right out of the box:
![image](https://user-images.githubusercontent.com/11830494/74795020-bed52800-52ff-11ea-8ada-bbaa04c42415.png)
Either you might have disabled the AE2 integration in the config file (`config\IntegrationForegoing.cfg`), or it might be some sort of file protection issues on your PC blocking the mod from generating the laser drill config. Because typically, you should see the custom laser configs in `config\laser_drill_ores`:
![image](https://user-images.githubusercontent.com/11830494/74795340-a0bbf780-5300-11ea-85bd-1df78894f222.png)
There's really not much I can do about it if this issue only happens to you and not everyone else since Industrial Foregoing is in charge of handling all of the laser drill configs, including the ones from my addon.

**Comment by GrantGryczan** [comment]
Oh! I'm sorry. I thought this was Industrial Foregoing. I must have misread it, since "Integration" looks so similar to "Industrial" at a glance, haha. I probably found this mod on the CurseForge page, thought it was vanilla IF, saw AE2 integration, clicked to the GitHub, and submitted this issue thinking vanilla IF was supposed to have AE2 integration.
