### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Archilyte** [JackyyTV/IntegrationForegoing#51]
[Crash Log](https://paste.dimdev.org/afakiyojon.mccrash)
i have no idea what is causing the crash other than this mod because vanillafix said so

**Comment by JackyyTV** [comment]
![image](https://user-images.githubusercontent.com/11830494/79231152-38b90600-7e98-11ea-9554-d03d4eebc24f.png)
You need to update Industrial Foregoing, this version you have is extremely outdated and doesn't have the new Laser Drill system, hence the crash since my addon mod only supports newer versions.

**Comment by Buuz135** [comment]
Literally a 3 year old version

**Comment by Archilyte** [comment]
...i downloaded the latest version yesterday...

...twitch wtf did u do?
whatever, i got the new version now
